config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		if @event.save
			redirect_to events_path
			flash[:notice] = "New Event Created"
		end
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
			if @event.update(event_params)
				redirect_to @event
				flash[:notice] = "Event Updated"
			end
	end

	def show
		@event = Event.find(params[:id])
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to events_path
		flash[:notice] = 'Event destroyed!'
	end

	private
	def event_params
		params.require(:event).permit(:name, :date, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :date %>
	<%= f.date_select :date, start_year: 2014, end_year: (Time.now.year + 5) %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.submit %>
<% end %>

app/views/events/index.html.erb
<% if flash[:notice] %>
  <p ><%= flash[:notice] %></p>
<% end %>

<h1>Events</h1>

<% @events.each do |event| %>


<h1><%= event.name %></h1>

<h3><%= event.date %></h3>

<h3><%= event.description %></h3>

<button><%=link_to('Edit Event', edit_event_path(event)) %></button>

<button>
	<%=link_to('Destroy Event', event, method: :delete, data: {confirm: "Are you sure you want to delete the '#{event.name}'' event?"}) %>
</button>

<% end %>

<br>
<button><%= link_to('New Event', new_event_path) %></button>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :date %>
	<%= f.date_select :date, start_year: 2014, end_year: (Time.now.year + 5) %>

	<%= f.label :description %>
	<%= f.text_area :description %>

	<%= f.submit %>
<% end %>

app/views/events/show.html.erb
<% if flash[:notice] %>
  <p ><%= flash[:notice] %></p>
<% end %>
<h1><%= @event.name %></h1>

<h3><%= @event.date %></h3>

<h3><%= @event.description %></h3>

<%= link_to('Back to Events', events_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Planner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>